-- Si se agregan nuevas tablas fijarse de ponerlas en orden,
--Ejemplo: Si la entidad 1 tiene una fk de la entidad 2, poner el DROP de la entidad 1 antes
-- que el de la entidad 2, de lo contrario va a saltar un error de dependencias.

DROP TABLE BUGDEVELOPING.AGENDA_DIA
DROP TABLE BUGDEVELOPING.DIA
DROP TABLE BUGDEVELOPING.BONO_CONSULTA
DROP TABLE BUGDEVELOPING.MEDICAMENTOS_X_RECETA
DROP TABLE BUGDEVELOPING.MEDICAMENTOS
DROP TABLE BUGDEVELOPING.RECETA_MEDICA
DROP TABLE BUGDEVELOPING.BONO_FARMACIA
DROP TABLE BUGDEVELOPING.COMPRA_BONO
DROP TABLE BUGDEVELOPING.BONO
DROP TABLE BUGDEVELOPING.COMPRA
DROP TABLE BUGDEVELOPING.CANCELACION_TURNO
DROP TABLE BUGDEVELOPING.CONSULTA
DROP TABLE BUGDEVELOPING.TURNO
DROP TABLE BUGDEVELOPING.AGENDA_PERSONAL
DROP TABLE BUGDEVELOPING.ESPECIALIDAD_MEDICO
DROP TABLE BUGDEVELOPING.ESPECIALIDAD
DROP TABLE BUGDEVELOPING.PLAN_HISTORIAL
DROP TABLE BUGDEVELOPING.FUNROL
DROP TABLE BUGDEVELOPING.FUNCIONALIDAD
DROP TABLE BUGDEVELOPING.TIPO_ESPECIALIDAD
DROP TABLE BUGDEVELOPING.MEDICO
DROP TABLE BUGDEVELOPING.PACIENTE
DROP TABLE BUGDEVELOPING.PERSONA
DROP TABLE BUGDEVELOPING.PLAN_MEDICO
DROP TABLE BUGDEVELOPING.USUARIO_ROL
DROP TABLE BUGDEVELOPING.ROL
DROP TABLE BUGDEVELOPING.USUARIO
DROP TABLE BUGDEVELOPING.TIPO_CANCELACION
DROP TABLE BUGDEVELOPING.ESTADO_CIVIL
DROP TABLE BUGDEVELOPING.SEXO
DROP TABLE BUGDEVELOPING.TIPO_DOCUMENTO


DROP PROCEDURE BUGDEVELOPING.MIGRAR_PERSONA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_PLAN_MEDICO
DROP PROCEDURE BUGDEVELOPING.MIGRAR_PACIENTE
DROP PROCEDURE BUGDEVELOPING.MIGRAR_MEDICO
DROP PROCEDURE BUGDEVELOPING.MIGRAR_TIPO_ESPECIALIDAD
DROP PROCEDURE BUGDEVELOPING.MIGRAR_ESPECIALIDAD
DROP PROCEDURE BUGDEVELOPING.MIGRAR_ESPECIALIDAD_MEDICO
DROP PROCEDURE BUGDEVELOPING.MIGRAR_BONO
DROP PROCEDURE BUGDEVELOPING.MIGRAR_BONO_CONSULTA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_BONO_FARMACIA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_CONSULTA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_TURNO
DROP PROCEDURE BUGDEVELOPING.MIGRAR_MEDICAMENTOS
DROP PROCEDURE BUGDEVELOPING.MIGRAR_RECETA_MEDICA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_MEDICAMENTOS_X_RECETA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_COMPRA
DROP PROCEDURE BUGDEVELOPING.MIGRAR_COMPRA_BONO
DROP PROCEDURE BUGDEVELOPING.MIGRAR_AGENDA_PERSONAL
DROP PROCEDURE BUGDEVELOPING.MIGRAR_DIA
DROP PROCEDURE BUGDEVELOPING.ACTUALIZAR_CONSULTA
DROP PROCEDURE BUGDEVELOPING.CONFECCIONAR_RECETA
DROP PROCEDURE BUGDEVELOPING.INSERTAR_PERSONA
DROP PROCEDURE BUGDEVELOPING.REGISTRAR_COMPRA
DROP PROCEDURE BUGDEVELOPING.DAR_BAJA_AFILIADO
DROP PROCEDURE BUGDEVELOPING.LIST1_PRI
DROP PROCEDURE BUGDEVELOPING.LIST1_SEG
DROP PROCEDURE BUGDEVELOPING.LIST2_PRI
DROP PROCEDURE BUGDEVELOPING.LIST2_SEG
DROP PROCEDURE BUGDEVELOPING.LIST3_PRI
DROP PROCEDURE BUGDEVELOPING.LIST3_SEG
DROP PROCEDURE BUGDEVELOPING.LIST4_PRI
DROP PROCEDURE BUGDEVELOPING.LIST4_SEG
DROP PROCEDURE BUGDEVELOPING.BAJA_PROFESIONAL
DROP PROCEDURE BUGDEVELOPING.CAMBIO_PLAN_MEDICO_PACIENTE

DROP VIEW BUGDEVELOPING.V_HorariosMedicos_AUX
DROP VIEW BUGDEVELOPING.V_MEDICO_AUX
DROP VIEW BUGDEVELOPING.V_MEDICO_ESPECIALIDAD_AUX
DROP VIEW BUGDEVELOPING.V_PACIENTE_AUX
DROP VIEW BUGDEVELOPING.V_PERSONAS_AUX
DROP VIEW BUGDEVELOPING.V_COMPRA_BONO_AUX
DROP VIEW BUGDEVELOPING.COMPRADOS_NO_POR_ELLOS

DROP FUNCTION BUGDEVELOPING.BUSCAR_TURNOS_DISPONIBLES
DROP FUNCTION BUGDEVELOPING.GENERAR_CALENDARIO
DROP FUNCTION BUGDEVELOPING.GENERAR_RANGO_FECHAS
DROP FUNCTION BUGDEVELOPING.GENERAR_RANGO_HORARIO

DROP SCHEMA BUGDEVELOPING